MoMA exploring data

Consolidate the dataset and explore the countries of artists. How they are distributed worldwide. It could be the RQ.

## Descriptive Statistics of the MoMA Dataset

The following code is used to analyze the Museum of Modern Art (MoMA) Collection dataset.

The code was developed using Python and the pandas library in order to generate descriptive statistics and better understand the structure of the dataset.

The code performs the following tasks:
- loads the dataset,
- displays the first rows of the data,
- examines dataset dimensions,
- checks missing values,
- generates descriptive statistics,
- and exports the statistical summary into the DATA folder.

The outputs are printed directly in the notebook to support interpretation and analysis.

In [8]:
import pandas as pd

# Load dataset
df = pd.read_csv("artists.csv")

# Display first rows
print("First 5 Rows:")
print(df.head())

# Dataset dimensions
print("\nDataset Shape:")
print(df.shape)

# Dataset information
print("\nDataset Information:")
print(df.info())

# Missing values
print("\nMissing Values:")
print(df.isnull().sum())

# Descriptive statistics
stats = df.describe(include='all')

print("\nDescriptive Statistics:")
print(stats)

# Save statistics
stats.to_csv("artists_statistics.csv")

print("\nStatistics saved as artists_statistics.csv")

First 5 Rows:
   Artist ID             Name Nationality Gender  Birth Year  Death Year
0          1   Robert Arneson    American   Male      1930.0      1992.0
1          2   Doroteo Arnaiz     Spanish   Male      1936.0         NaN
2          3      Bill Arnold    American   Male      1941.0         NaN
3          4  Charles Arnoldi    American   Male      1946.0         NaN
4          5      Per Arnoldi      Danish   Male      1941.0         NaN

Dataset Shape:
(15091, 6)

Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15091 entries, 0 to 15090
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Artist ID    15091 non-null  int64
 1   Name         15091 non-null  object
 2   Nationality  12603 non-null  object
 3   Gender       12019 non-null  object
 4   Birth Year   11237 non-null  float64
 5   Death Year   4579 non-null   float64
dtypes: float64(2), int64(1), object(3)
memory usage: 707.5+ KB
None

Missing Values:
Artist ID          0
Name               0
Nationality     2488
Gender          3072
Birth Year      3854
Death Year     10512
dtype: int64

Descriptive Statistics:
           Artist ID              Name Nationality Gender    Birth Year  \
count   15091.000000             15091       12603  12019  11237.000000
unique           NaN             15039         125      3           NaN
top              NaN  Unknown Designer    American   Male           NaN
freq             NaN                24        5198   9820           NaN
mean    18297.556027               NaN         NaN    NaN   1930.852719
std     16632.963898               NaN         NaN    NaN     34.531997
min         1.000000               NaN         NaN    NaN   1730.000000
25%      4195.500000               NaN         NaN    NaN   1910.000000
50%      8593.000000               NaN         NaN    NaN   1936.000000
75%     33088.500000               NaN         NaN    NaN   1956.000000
max     67695.000000               NaN         NaN    NaN   2012.000000

         Death Year
count   4579.000000
unique          NaN
top             NaN
freq            NaN
mean    1974.287399
std       31.153665
min     1795.000000
25%     1958.000000
50%     1980.000000
75%     1998.000000
max     2017.000000

Statistics saved as artists_statistics.csv

In [9]:
print(df.shape)

(15091, 6)

# Museum of Modern Art (MoMA) Artist Dataset Analysis

## Project Description

## Research Purpose

## Data Origin

## Research Questions

# Workflow

## 1. Data Access

## 2. Data Exploration

## 3. Cleaning / Preprocessing

## 4. Preparing Data for Wikidata

## 5. Data Enrichment

## 6. Analysis

## Results

## Key Findings

In [1]:
import pandas as pd

# Load the dataset
df = pd.read_csv("../data/artists.csv")

print("Dataset loaded successfully!")

Dataset loaded successfully!

In [2]:
# Display first 10 rows
df.head(10)

   Artist ID             Name Nationality  Gender  Birth Year  Death Year
0          1   Robert Arneson    American    Male      1930.0      1992.0
1          2   Doroteo Arnaiz     Spanish    Male      1936.0         NaN
2          3      Bill Arnold    American    Male      1941.0         NaN
3          4  Charles Arnoldi    American    Male      1946.0         NaN
4          5      Per Arnoldi      Danish    Male      1941.0         NaN
5          6    Danilo Aroldi     Italian    Male      1925.0         NaN
6          7        Bill Aron    American    Male      1941.0         NaN
7          9    David Aronson    American    Male      1923.0         NaN
8         10    Irene Aronson    American  Female      1918.0         NaN
9         11  Jean (Hans) Arp      French    Male      1886.0      1966.0

In [3]:
# Number of rows and columns
print("Dataset shape:")
print(df.shape)

Dataset shape:
(15091, 6)

In [4]:
# Column names
print(df.columns)

Index(['Artist ID', 'Name', 'Nationality', 'Gender', 'Birth Year',
       'Death Year'],
      dtype='object')

In [5]:
# Information about the dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15091 entries, 0 to 15090
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Artist ID    15091 non-null  int64
 1   Name         15091 non-null  object
 2   Nationality  12603 non-null  object
 3   Gender       12019 non-null  object
 4   Birth Year   11237 non-null  float64
 5   Death Year   4579 non-null   float64
dtypes: float64(2), int64(1), object(3)
memory usage: 707.5+ KB

In [6]:
missing = df.isnull().sum()

print(missing)

Artist ID          0
Name               0
Nationality     2488
Gender          3072
Birth Year      3854
Death Year     10512
dtype: int64

In [7]:
statistics = pd.DataFrame({

    "Column": df.columns,

    "Missing Values": df.isnull().sum().values,

    "Unique Values": df.nunique().values

})

statistics

        Column  Missing Values  Unique Values
0    Artist ID               0          15091
1         Name               0          15039
2  Nationality            2488            125
3       Gender            3072              3
4   Birth Year            3854            228
5   Death Year           10512            165

In [8]:
statistics.to_csv("../data/artists_statistics.csv", index=False)

print("artists_statistics.csv created successfully!")

artists_statistics.csv created successfully!

In [9]:
complete = df.dropna(subset=[
    "Artist ID",
    "Name",
    "Nationality",
    "Gender",
    "Birth Year",
    "Death Year"
])

complete.to_csv("../data/artists_all_fields_complete.csv", index=False)

print("Complete artists:", len(complete))

Complete artists: 4429

In [10]:
missing_dates = df[
    df["Birth Year"].isna() |
    df["Death Year"].isna()
]

missing_dates.to_csv("../data/artists_missing_dates.csv", index=False)

print("Artists needing enrichment:", len(missing_dates))

Artists needing enrichment: 10525

In [11]:
prepared = missing_dates.copy()

prepared["wikidata_id"] = ""

prepared["match_status"] = ""

prepared["source"] = ""

prepared.to_csv("../data/artists_prepared_for_wikidata.csv", index=False)

print("artists_prepared_for_wikidata.csv created!")

artists_prepared_for_wikidata.csv created!